INFO     log:logger_utils.py:20 ----------------编辑标签接口测试开始----------------
INFO     log:logger_utils.py:20 headers没有value,请确认
INFO     log:logger_utils.py:20 请求方式：post
INFO     log:logger_utils.py:20 请求地址：https://api.weixin.qq.com/cgi-bin/tags/update
INFO     log:logger_utils.py:20 headers未填充，或者(反例)设计为空
INFO     log:logger_utils.py:20 请求params参数：{'access_token': '62_r-mXehmonHBl0_VgyH7t0SCVsdHeyPEF_bWqlgfVl0uLuPOZxXL5k2iWlURSVufYJ2mkNKAfL6hneuTCwQKcrth5IJp4eymELfbAeWiL5DQhTYeCDp-G_DxHY3oXMXaADARGR'}
INFO     log:logger_utils.py:20 请求json参数：{'tag': {'id': 134, 'name': '广东人8581}'}}
INFO     log:logger_utils.py:20 预期结果：[{'equals': {'errcode': 0}}, {'codes': {'status_code': 200}}]
INFO     log:logger_utils.py:20 实际结果：{'errcode': -1, 'errmsg': 'system error hint: [yihfnE6Vf-h5fL.A] rid: 6373608c-79597597-03c8625f'},status_code:200
INFO     log:logger_utils.py:20 执行相等断言
INFO     log:logger_utils.py:20 equals断言失败：errcode不等于0
INFO     log:logger_utils.py:20 执行状态码断言
INFO     log:logger_utils.py:20 编辑标签业务断言失败
ERROR    log:logger_utils.py:15 requests_utils模块standard_yaml_testcase方法报错：Traceback (most recent call last):
  File "D:\Python_project\ms-jiekou\commons\requests_util.py", line 83, in standard_yaml_testcase
    assert 1 == 2, print_log("{}业务断言失败".format(caseinfo["name"]))
AssertionError: None