[2022-11-13 23:05:15,925] logger_utils.py->print_log line:20 [INFO]----------------获取鉴权码-正例接口测试开始----------------
[2022-11-13 23:05:15,926] logger_utils.py->print_log line:20 [INFO]请求方式：None
[2022-11-13 23:05:15,926] logger_utils.py->print_log line:20 [INFO]请求地址：https://api.weixin.qq.com/cgi-bin/token
[2022-11-13 23:05:15,926] logger_utils.py->print_log line:20 [INFO]请求params参数：{'grant_type': 'client_credential', 'appid': 'wxf393fadf3268a5d5', 'secret': 'e9a29dfa3920020ebee3675bcc9c2cf8'}
[2022-11-13 23:05:16,238] logger_utils.py->print_log line:20 [INFO]预期结果：[{'codes': {'status_code': 200}}, {'contains': '$ddt{assert_str}'}]
[2022-11-13 23:05:16,239] logger_utils.py->print_log line:20 [INFO]实际结果：{'access_token': '62_q1_wrfAKkTWbpkxdhHzwvELaIzWubGVhRmwdZFcRsW7CsMGwxt6o9dPz51hSTeFLcLV88fLEE8HK_3oznk2pR14gZaDWOtpYR1wqwBL-yKI5O9ccs-YvRBPqrVsOCPiAGACQD', 'expires_in': 7200},status_code:200
[2022-11-13 23:05:16,239] logger_utils.py->print_log line:20 [INFO]状态码断言
[2022-11-13 23:05:16,239] logger_utils.py->print_log line:20 [INFO]包含断言
[2022-11-13 23:05:16,239] logger_utils.py->print_log line:20 [INFO]contains断言失败：返回的结果中没有$ddt{assert_str}
[2022-11-13 23:05:16,239] logger_utils.py->print_log line:20 [INFO]获取鉴权码-正例业务断言失败
[2022-11-13 23:05:16,240] logger_utils.py->error_log line:15 [ERROR]requests_utils模块standard_yaml_testcase方法报错：Traceback (most recent call last):
  File "D:\Python_project\ms-jiekou\commons\requests_util.py", line 74, in standard_yaml_testcase
    assert 1 == 2, print_log("{}业务断言失败".format(caseinfo["name"]))
AssertionError: None

[2022-11-13 23:05:16,387] logger_utils.py->print_log line:20 [INFO]----------------获取鉴权码-secret为空接口测试开始----------------
[2022-11-13 23:05:16,387] logger_utils.py->print_log line:20 [INFO]请求方式：None
[2022-11-13 23:05:16,388] logger_utils.py->print_log line:20 [INFO]请求地址：https://api.weixin.qq.com/cgi-bin/token
[2022-11-13 23:05:16,388] logger_utils.py->print_log line:20 [INFO]请求params参数：{'grant_type': 'client_credential', 'appid': 'wxf393fadf3268a5d5', 'secret': ''}
[2022-11-13 23:05:17,229] logger_utils.py->print_log line:20 [INFO]正则表达式"access_token":"(.*?)"可能有误，或者(反例)接口请求失败，未提取到中间变量
[2022-11-13 23:05:17,229] logger_utils.py->print_log line:20 [INFO]jsonpath表达式$..expires_in可能有误，或者(反例)接口请求失败，未提取到中间变量
[2022-11-13 23:05:17,229] logger_utils.py->print_log line:20 [INFO]预期结果：[{'codes': {'status_code': 200}}, {'contains': '$ddt{assert_str}'}]
[2022-11-13 23:05:17,229] logger_utils.py->print_log line:20 [INFO]实际结果：{'errcode': 41004, 'errmsg': 'appsecret missing rid: 637107ab-76d4f511-79cd280a'},status_code:200
[2022-11-13 23:05:17,229] logger_utils.py->print_log line:20 [INFO]状态码断言
[2022-11-13 23:05:17,229] logger_utils.py->print_log line:20 [INFO]包含断言
[2022-11-13 23:05:17,229] logger_utils.py->print_log line:20 [INFO]contains断言失败：返回的结果中没有$ddt{assert_str}
[2022-11-13 23:05:17,229] logger_utils.py->print_log line:20 [INFO]获取鉴权码-secret为空业务断言失败
[2022-11-13 23:05:17,230] logger_utils.py->error_log line:15 [ERROR]requests_utils模块standard_yaml_testcase方法报错：Traceback (most recent call last):
  File "D:\Python_project\ms-jiekou\commons\requests_util.py", line 74, in standard_yaml_testcase
    assert 1 == 2, print_log("{}业务断言失败".format(caseinfo["name"]))
AssertionError: None

